### ISSUE TITLE
why ypkg

### ISSUE THREAD

**Issue by AkgunFatih** [Justinzobel/solus-dde#3]
why do you use ypkg when building it

**Comment by Justinzobel** [comment]
Because of the way the staging system works in Ashtray. I wasn't aware you
were still wanting to work with us.

**Comment by AkgunFatih** [comment]
there is no need to work on deepin 11+
i am waiting for stable release of deepin 20

the beta packages are here https://community-packages.deepin.com/deepin/pool/main/d/

they will release it on github as soon as they hit the stable release

**Comment by Justinzobel** [comment]
Deepin 20 is the OS. The desktop version is at 5.x

**Comment by AkgunFatih** [comment]
yes but im wating for the new releases
they now use dtkgui with dtkwidget
